config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  get 'markers/:id/update', to: 'markers#update'
  get 'markers/:id/destroy', to: 'markers#destroy'
  resources :maps do
    resources :events, only: :index
    resources :markers, shallow: true
  end
  resources :events
  root 'maps#index'

end

app/models/map.rb
class Map < ActiveRecord::Base
  attr_accessor :raw_address
  has_many :markers
  belongs_to :user
  has_many :events, dependent: :destroy
  
  geocoded_by :raw_address
  reverse_geocoded_by :latitude, :longitude

  after_validation -> {
    self.address = self.raw_address
    geocode
  }, if: ->(obj){ obj.raw_address.present? and obj.raw_address != obj.address }

  after_validation :reverse_geocode, unless: ->(obj) { obj.raw_address.present? },
                   if: ->(obj){ obj.latitude.present? and obj.latitude_changed? and obj.longitude.present? and obj.longitude_changed? }
  def self.coordinates(map_id)
    latitude = Marker.where("map_id = ?", map_id).pluck(:latitude)
    longitude = Marker.where("map_id = ?", map_id).pluck(:longitude)
    coordinates = latitude.zip(longitude)
    coordinates
  end

  def self.info(map_id)
    info = Marker.where("map_id = ?", map_id).pluck(:info)
    info
  end
  
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  #prepend_before_action
  before_action :authenticate_user!

  def index
    @maps = current_user.maps.order('created_at DESC')
    @email = current_user.email
  end

  def new
    @map = current_user.maps.build
  end

  def show
    @map = Map.find(params[:id])
    gon.lat = @map.latitude
    gon.lng = @map.longitude
    @marker = Marker.new
    @markers = Marker.where(map_id: @map)
    gon.info = Map.info(@map)
    @mark = Marker.marker_id(@map)
    gon.map_id = params[:id]
    gon.markerId = Marker.marker_id(@map)
    gon.place_id = Marker.place_id(@map)
    gon.marker = params[:marker_id]
  end

  def create
    @map = current_user.maps.build(map_params)
    if @map.save
      flash[:success] = "Map Added"
      redirect_to root_path
    else
      render 'new'
    end
  end

  def update
    @map = Map.find(params[:id])
    @marker = @map.markers.find_by map_id: @map
    if @map.update(map_params)
      redirect_to map_marker_path(params[:id])
    end
  end

  def destroy
    @map = Map.find(params[:id])
    @map.destroy
    redirect_to root_path
  end

  private

  def map_params
    params.require(:map).permit(:title, :raw_address, :latitude, :longitude)
  end


end

app/helpers/maps_helper.rb
module MapsHelper
end

app/views/maps/_form.html.erb
<%= form_for @map do |f| %>
  <div class="field form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :raw_address, 'Address' %>
    <%= f.text_field :raw_address, class: "form-control" %>
  </div>
  <%= f.submit 'Add!', class: 'btn btn-success' %>
<% end %>

app/views/maps/_map.html.erb
<li>
  <%= link_to map.title, map_path(map), class: "btn btn-default" %>
  <%= link_to "Delete", map_path(map), method: :delete, data: {confirm: "are you sure?"}, class: "btn btn-default" %>
  <%= link_to 'Calender', map_events_path(map), class: "btn btn-default" %>
</li>

app/views/maps/index.html.erb
<span><%= @user %></span>
<h1>Maps</h1>

<%= link_to "Add Map", new_map_path, class: "btn btn-success" %>
<%= render @maps %>

app/views/maps/new.html.erb
<h1>Add Map</h1>
<%= render 'form' %>

app/views/maps/show.html.erb
<div class="jumbotron">
  <h1 class="display-3"><%= @map.title %></h1>
</div>
<div class="btn-group" role="group">
  <%= link_to "Back To Maps", maps_path, class: 'btn btn-default btn-lg' %>
  <button class="btn btn-default btn-lg"><%= link_to "Show Markers", controller: "markers", action: "index", map_id: @map %></button>
  <%= link_to "Calendar", map_events_path(@map), class: 'btn btn-default btn-lg'  %>
</div>


<div id="form">
  <%= render 'markers/form' %>
</div>

<!-- <script id="travelMode" type="text/x-handlebars-template">
  <div class="directionForm">
    <h2>Mode of Travel: </h2>
    <select id="mode">
      <option value="DRIVING">Driving</option>
      <option value="WALKING">Walking</option>
      <option value="BICYCLING">Bicycling</option>
      <option value="TRANSIT">Transit</option>
    </select>
    <button class='directionsBtn' class='btn btn-success'>Get Directions</button>
  </div>
</script> -->
<!-- <div id="directionForm" class="field form-group">
  <label for="mode">Mode of Travel: </label>
  <select id="mode", class="form-control">
    <option value="DRIVING">Driving</option>
    <option value="WALKING">Walking</option>
    <option value="BICYCLING">Bicycling</option>
    <option value="TRANSIT">Transit</option>
  </select>
  <button id="directionsBtn" class="btn-default">Get Directions</button>
</div> -->
<aside>
  <input id="searchTxt" class="form-control" type="text" placeholder="Search Nearby">
  <button id="clearSearch" class="btn">Clear</button>
</aside>
<div id="map"></div>
<div id="right-panel"></div>

  <%= javascript_include_tag 'http://maps.googleapis.com/maps/api/js?key=AIzaSyCq9JRLgL2ATvunEN0vRZ7g3fBeBiVznUo&libraries=places&callback=initialize' %>