config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  get 'markers/:id/update', to: 'markers#update'
  get 'markers/:id/destroy', to: 'markers#destroy'
  resources :maps do
    resources :events, only: :index
    resources :markers, shallow: true
  end
  resources :events
  root 'maps#index'

end

app/models/marker.rb
class Marker < ActiveRecord::Base
  belongs_to :map
attr_accessor :raw_address


   geocoded_by :raw_address
  reverse_geocoded_by :latitude, :longitude

  after_validation -> {
    self.address = self.raw_address
    geocode
  }, if: ->(obj){ obj.raw_address.present? and obj.raw_address != obj.address }

  after_validation :reverse_geocode, unless: ->(obj) { obj.raw_address.present? },
                   if: ->(obj){ obj.latitude.present? and obj.latitude_changed? and obj.longitude.present? and obj.longitude_changed? }
  def self.marker_id(map_id)
    marker_id = Marker.where("map_id = ?", map_id).pluck(:id)
    marker_id
  end

  def self.place_id(map_id)
    place_id = Marker.where("map_id = ?", map_id).pluck(:place_id)
    place_id
  end
 
 
end

app/controllers/markers_controller.rb
class MarkersController < ApplicationController
  before_action :set_marker, only: [:show, :edit, :update, :destroy]
  #before_action :set_map
  # GET /markers
  # GET /markers.json
  def index
    @map = Map.find(params[:map_id])
    # @markers = Marker.all
    @markers = Marker.where(map_id: @map)
   # @map = params[:map_id]
  end

  # GET /markers/1
  # GET /markers/1.json
  def show
    @map = Map.find(@marker.map_id)
  end

  # GET /markers/new
  def new
    #@map = Map.find(params[:map_id])
    @marker = Marker.new
   # @map = params[:map_id]
  end

  # GET /markers/1/edit
  def edit
    @map = Map.find(@marker.map_id)
  end

  # POST /markers
  # POST /markers.json
  def create
    
    @marker = Marker.new(marker_params)
    @map = Map.find(@marker.map_id)
    @markers = Marker.where(map_id: @map)
    gon.place_id = params[:place_id]
    respond_to do |format|
      if @marker.save
        format.html { redirect_to map_url }
        format.js
        format.json { render action: 'show', status: :created, location: @markers }
      else
        format.html { render action: 'new' }
        format.json { render json: @marker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /markers/1
  # PATCH/PUT /markers/1.json
  def update
    @map = Map.find(@marker.map_id)
    @markers = Marker.where(map_id: @map)
    respond_to do |format|
      if @marker.update_attributes(marker_params)
        format.html { redirect_to map_url(@map), notice: 'Marker was successfully updated.' }
        format.js

      else
        format.html { render :edit }
        format.json { render json: @marker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /markers/1
  # DELETE /markers/1.json
  def destroy
    @map = Map.find(@marker.map_id)
    respond_to do |format|
      if @marker.destroy
        format.html { redirect_to map_path(@map), notice: 'Marker was successfully destroyed.' }
      else
        format.html { redirect_to map_url, notice: 'Marker was Not successfully destroyed.' }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_marker
      @marker = Marker.find(params[:id])
    end

    # def set_map
    #   @map = params[:map]
    # end

    # Never trust parameters from the scary internet, only allow the white list through.
    def marker_params
      params.require(:marker).permit(:title, :raw_address, :latitude, :longitude, :info, :map_id, :place_id)
    end
end

app/helpers/markers_helper.rb
module MarkersHelper
end

app/views/markers/_edit_form.html.erb
<%= form_for(@marker, :url => marker_path(@marker)) do |f| %>
  <% if @marker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@marker.errors.count, "error") %> prohibited this marker from being saved:</h2>

      <ul>
      <% @marker.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :info %><br>
    <%= f.text_area :info, class: "form-control" %>
  </div>

  <div class="actions" id="markerFormSubmit">
    <%= f.submit 'Edit Marker', class: 'btn btn-success'%>
  </div>
<% end %>

app/views/markers/_form.html.erb
<%= form_for(@marker, :url => map_markers_path(@map), remote: true) do |f| %>
  <% if @marker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@marker.errors.count, "error") %> prohibited this marker from being saved:</h2>

      <ul>
      <% @marker.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :raw_address %><br>
    <%= f.text_field :raw_address, class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.hidden_field :latitude, value: @marker.latitude %>
  </div>
  <div class="field form-group">
    <%= f.hidden_field :longitude, value: @marker.longitude  %>
  </div>
  <div class="field form-group">
    <%= f.label :info %><br>
    <%= f.text_area :info, class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.hidden_field :map_id, :value => @map.id %>
  </div>
  <div class="field form-group">
    <%= f.hidden_field :place_id %>
  </div>
  <div class="actions" id="markerFormSubmit">
    <%= f.submit 'Add Marker', class: 'btn btn-success'%>
  </div>
<% end %>
  <script type="text/javascript">
    $("textarea").jqte({
      "strike" : false,
      "source" : false,
      "remove" : false,
      "sub" : false,
      "sup" : false,
      "format" : false
    });
  </script>

app/views/markers/_marker.html.erb
<tr>
  <td>
    <%= marker.title %>
  </td>
  <td>
    <%= marker.address %>
  </td>
  <td>
    <%= marker.latitude %>
  </td>
  <td>
    <%= marker.longitude %>
  </td>
  <td>
    <%= marker.info %>
  </td>
  <td>
    <%= marker.map_id %>
  </td>
  <td class="place">
    <%=marker.place_id %>
  </td>
  <td>
    <%= link_to 'Show', marker_path(marker.id), class: "btn btn-default" %>
  </td>
  <td>
    <%= link_to 'Destroy', marker_path(marker), controller: 'markers', method: :delete, class: "btn btn-default" %>
  </td>
  <td class="place">
    <%=marker.id %>
  </td>
</tr>

app/views/markers/_new.html.erb
<h1>New Marker</h1>

<%= render 'form' %>

<%= link_to 'Back', maps_path %>

app/views/markers/create.js.erb
$('#markers').html("<%=escape_javascript render(@markers)%>");

app/views/markers/edit.html.erb
<h1>Editing Marker</h1>

<%= render 'edit_form' %>

<%= link_to 'Show', @map, class: "btn btn-default" %> 

app/views/markers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Markers</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Address</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Info</th>
      <th>Map</th>
      <th>ID</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @markers.each do |marker| %>
      <tr>
        <td><%= marker.title %></td>
        <td><%= marker.address %></td>
        <td><%= marker.latitude %></td>
        <td><%= marker.longitude %></td>
        <td><%= marker.info %></td>
        <td><%= marker.map_id %></td>
        <td><%= marker.id %></td>
        <td><%= link_to 'Show', marker_path(marker), controller: 'markers',action: 'show', class: "btn btn-default"  %></td>
        <td><%= link_to 'Edit', edit_marker_path(marker), class: "btn btn-default" %></td>
        <td><%= link_to 'Destroy', marker_path(marker), controller: 'markers', method: :delete, class: "btn btn-default" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/markers/new.html.erb
<h1>New Marker</h1>
<%= render 'form' %>

<%= link_to 'Back', maps_path, class: "btn btn-default" %>

app/views/markers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @marker.title %>
</p>

<p>
  <strong>Address:</strong>
  <%= @marker.address %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @marker.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @marker.longitude %>
</p>

<p>
  <strong>Info:</strong>
  <%= @marker.info %>
</p>

<p>
  <strong>Map:</strong>
  <%= @marker.map_id %>
</p>

<p>
  <strong>place:</strong>
  <%= @marker.place_id %>
</p>

<%= link_to 'Edit', edit_marker_path(@marker), class: "btn btn-default" %>
<%= link_to 'Delete', marker_path(@marker.id), class: "btn btn-default" %>
<%= link_to 'Show Markers', map_markers_path(@marker.map_id), class: "btn btn-default" %>

app/views/markers/update.js.erb
$('#markers').html("<%=escape_javascript render(@markers)%>");