config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  get 'markers/:id/update', to: 'markers#update'
  get 'markers/:id/destroy', to: 'markers#destroy'
  resources :maps do
    resources :events, only: :index
    resources :markers, shallow: true
  end
  resources :events
  root 'maps#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
 belongs_to :map

  has_attached_file :document
  validates_attachment :document, :content_type => { :content_type => %w(application/pdf application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document) }
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token, only: [:create]

  # GET /events
  # GET /events.json
  def index
    @map = params[:map_id]
    @marker = params[:marker_id]
    @events = Event.all
    @events = Event.where(map_id: @map)
  end

  # GET /events/1
  # GET /events/1.json`
  def show
    @map = params[:map_id]
  end

  # GET /events/new
  def new
    @map = params[:map_id]
    @marker = params[:marker_id]
    @event = Event.new
    @date = params[:date].to_date
  end

  # GET /events/1/edit
  def edit
    @marker = params[:marker_id]
    @map = params[:map_id]
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @map = params[:map_id]
    @event.destroy
    respond_to do |format|
      format.html { redirect_to map_events_path(@event.map_id), notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :start_time, :end_time, :document, :map_id, :marker_id)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for @event, html: { multipart: true } do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.hidden_field :map_id, value: @map %>
  </div>
  <div class="field form-group">
    <%= f.hidden_field :marker_id, value: @marker %>
  </div>
  <div class="field form-group">
    <p>Start Date: <%= @date %></p>
    <%= f.date_select :start_time, default: @date %>
  </div>
  <div class="field form-group">
    <%= f.label :end_time, 'End Date:' %><br>
    <%= f.date_select :end_time , default: @date %>
  </div>
  <div class="field form-group">
    <%= f.label :document %><br>
    <%= f.file_field :document, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit 'New Event' , class: "btn btn-default"%>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event, class: "btn btn-default" %> |
<%= link_to 'Back', events_path, class: "btn btn-default" %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Calendar</h1>
<h3><%= link_to "My Maps", maps_path, class: "btn btn-default" %></h3>
<table>
  <% @events.each do |event| %>
    <tr>
      <td>
        <%= link_to event.name, event %>
      </td>
      <td>
        <%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" %>
      </td>
    </tr>
  <% end %>
</table>

<%= month_calendar events: @events do |date, events| %>
  <%= date %>
  <br/>
  <% events.each do |event| %>
    <div class="btn-toolbar" role="toolbar">
      <%= link_to event.name, event, class: "btn btn-sm" %>
      <%= link_to 'Edit', edit_event_path(event, map_id: @map), class: "btn btn-sm"%>
      <%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm"%>
    </div>
  <% end %>
  <%= link_to 'New Event', new_event_path(date: date, map_id: @map), class: "btn btn-sm btn-default"%>
<% end %>
<br>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path, class: "btn btn-default" %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @event.start_time %>
</p>

<p>
  <strong>Map ID:</strong>
  <%= @event.map_id %>
</p>

<p>
  <strong>Marker ID:</strong>
  <%= @event.marker_id %>
</p>

<p>
  <strong>End time:</strong>
  <%= @event.end_time %>
</p>

<p>
  <strong>Document:</strong>
  <%= link_to 'Document', @event.document.url, class: "btn btn-default" %>
</p>
<%= link_to 'Show on Map', map_path(@event.map_id, marker_id: @event.marker_id), class: "btn btn-default" %> |
<%= link_to 'Edit', edit_event_path(@event), class: "btn btn-default" %> |
<%= link_to 'Back', map_events_path(@event.map_id, @map), class: "btn btn-default" %>